"""
Scene Validation: Geometry and Physics Consistency Checks
Validates 3D scenes generated by World Models for consistency.
"""

import json
import numpy as np
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass
from pathlib import Path
import trimesh
import open3d as o3d


@dataclass
class ValidationResult:
    """Result of a validation check."""
    check_name: str
    passed: bool
    score: float  # 0.0 - 1.0
    details: Dict[str, Any]
    message: str


class SceneValidator:
    """Validates 3D scene geometry and physics consistency."""

    def __init__(self, scene_path: str):
        self.scene_path = Path(scene_path)
        self.scene = None
        self.mesh = None
        self.point_cloud = None
        self._load_scene()

    def _load_scene(self):
        """Load scene from file (GLB, OBJ, PLY, etc.)."""
        try:
            # Try trimesh first (handles GLB, OBJ, etc.)
            self.scene = trimesh.load(self.scene_path, force='scene')
            if isinstance(self.scene, trimesh.Scene):
                # Merge all meshes
                self.mesh = trimesh.util.concatenate(
                    [geom for geom in self.scene.geometry.values()]
                )
            else:
                self.mesh = self.scene

            # Also load as point cloud for some checks
            self.point_cloud = o3d.io.read_point_cloud(str(self.scene_path))

        except Exception as e:
            raise RuntimeError(f"Failed to load scene: {e}")

    # === Geometry Consistency Checks ===

    def check_watertight(self) -> ValidationResult:
        """Check if mesh is watertight (no holes)."""
        if self.mesh is None:
            return ValidationResult("watertight", False, 0.0, {}, "No mesh loaded")

        is_watertight = self.mesh.is_watertight
        score = 1.0 if is_watertight else 0.0

        return ValidationResult(
            "watertight",
            is_watertight,
            score,
            {"euler_number": self.mesh.euler_number if hasattr(self.mesh, 'euler_number') else None},
            "Mesh is watertight" if is_watertight else "Mesh has holes/boundary edges"
        )

    def check_manifold(self) -> ValidationResult:
        """Check if mesh is 2-manifold."""
        if self.mesh is None:
            return ValidationResult("manifold", False, 0.0, {}, "No mesh loaded")

        # Check for non-manifold edges
        try:
            non_manifold_edges = self.mesh.edges[~self.mesh.is_edge_manifold]
            is_manifold = len(non_manifold_edges) == 0
            score = 1.0 if is_manifold else max(0.0, 1.0 - len(non_manifold_edges) / 1000)
        except:
            is_manifold = True
            score = 1.0

        return ValidationResult(
            "manifold",
            is_manifold,
            score,
            {"non_manifold_edge_count": len(non_manifold_edges) if not is_manifold else 0},
            "Mesh is 2-manifold" if is_manifold else f"Found {len(non_manifold_edges)} non-manifold edges"
        )

    def check_normals_consistency(self) -> ValidationResult:
        """Check if face normals are consistent (no flipped faces)."""
        if self.mesh is None:
            return ValidationResult("normals", False, 0.0, {}, "No mesh loaded")

        # Check for adjacent faces with opposing normals
        try:
            face_normals = self.mesh.face_normals
            # Simplified: check if normals are roughly consistent
            # (real implementation would check adjacency)
            normal_variance = np.var(face_normals, axis=0).mean()
            is_consistent = normal_variance < 0.5  # Threshold
            score = max(0.0, 1.0 - normal_variance)
        except:
            is_consistent = True
            score = 1.0

        return ValidationResult(
            "normals_consistency",
            is_consistent,
            score,
            {"normal_variance": float(normal_variance) if 'normal_variance' in locals() else 0},
            "Normals are consistent" if is_consistent else "Normals have inconsistencies"
        )

    def check_self_intersection(self) -> ValidationResult:
        """Check for self-intersections in mesh."""
        if self.mesh is None:
            return ValidationResult("self_intersection", False, 0.0, {}, "No mesh loaded")

        try:
            # Use trimesh's self-intersection check (may be slow for large meshes)
            has_intersections = self.mesh.has_self_intersection
            score = 0.0 if has_intersections else 1.0
        except:
            # Fallback: bounding box overlap check
            has_intersections = False
            score = 1.0

        return ValidationResult(
            "self_intersection",
            not has_intersections,
            score,
            {},
            "No self-intersections" if not has_intersections else "Self-intersections detected"
        )

    def check_scale_consistency(self, expected_scale: float = 1.0) -> ValidationResult:
        """Check if scene scale is consistent with expected real-world scale."""
        if self.mesh is None:
            return ValidationResult("scale", False, 0.0, {}, "No mesh loaded")

        bounds = self.mesh.bounds
        extents = bounds[1] - bounds[0]
        max_extent = np.max(extents)

        # Check if max extent is reasonable (not tiny or huge)
        # Assuming metric units: reasonable range 0.01m to 100m
        is_reasonable = 0.01 <= max_extent <= 100
        scale_ratio = max_extent / expected_scale if expected_scale > 0 else 1.0
        score = 1.0 if is_reasonable else max(0.0, 1.0 - abs(np.log10(scale_ratio)))

        return ValidationResult(
            "scale_consistency",
            is_reasonable,
            score,
            {"max_extent": float(max_extent), "extents": extents.tolist(), "scale_ratio": float(scale_ratio)},
            f"Scale reasonable: {max_extent:.2f}m max extent" if is_reasonable else f"Scale unrealistic: {max_extent:.2f}m"
        )

    # === Physics Consistency Checks ===

    def check_center_of_mass(self) -> ValidationResult:
        """Check if center of mass is within convex hull (stable)."""
        if self.mesh is None:
            return ValidationResult("center_of_mass", False, 0.0, {}, "No mesh loaded")

        try:
            com = self.mesh.center_mass
            # Check if COM is inside convex hull
            hull = self.mesh.convex_hull
            is_inside = hull.contains([com])[0]
            score = 1.0 if is_inside else 0.5
        except:
            com = [0, 0, 0]
            is_inside = True
            score = 1.0

        return ValidationResult(
            "center_of_mass",
            is_inside,
            score,
            {"center_of_mass": com.tolist() if hasattr(com, 'tolist') else com},
            "COM inside convex hull" if is_inside else "COM outside convex hull (unstable)"
        )

    def check_moment_of_inertia(self) -> ValidationResult:
        """Check if moment of inertia tensor is positive definite."""
        if self.mesh is None:
            return ValidationResult("moment_of_inertia", False, 0.0, {}, "No mesh loaded")

        try:
            inertia = self.mesh.moment_inertia
            eigenvals = np.linalg.eigvals(inertia)
            is_positive_definite = np.all(eigenvals > 0)
            score = 1.0 if is_positive_definite else 0.0
        except:
            is_positive_definite = True
            score = 1.0
            eigenvals = [1, 1, 1]

        return ValidationResult(
            "moment_of_inertia",
            is_positive_definite,
            score,
            {"eigenvalues": eigenvals.tolist() if hasattr(eigenvals, 'tolist') else eigenvals},
            "Inertia tensor positive definite" if is_positive_definite else "Inertia tensor not positive definite"
        )

    def check_physics_materials(self) -> ValidationResult:
        """Check if physics materials are assigned and reasonable."""
        if self.scene is None or not isinstance(self.scene, trimesh.Scene):
            return ValidationResult("physics_materials", True, 1.0, {}, "No scene metadata")

        # Check for material properties in scene metadata
        has_materials = False
        material_props = {}

        for name, geom in self.scene.geometry.items():
            if hasattr(geom, 'metadata') and geom.metadata:
                mat = geom.metadata.get('physics_material') or geom.metadata.get('material')
                if mat:
                    has_materials = True
                    material_props[name] = mat

        # Default to pass if no physics metadata (not required for all use cases)
        score = 1.0 if has_materials else 0.8

        return ValidationResult(
            "physics_materials",
            True,  # Not a hard failure
            score,
            {"materials_found": has_materials, "material_count": len(material_props)},
            f"Found {len(material_props)} physics materials" if has_materials else "No physics materials assigned"
        )

    # === Multi-View Consistency ===

    def check_multi_view_consistency(self, views_dir: str) -> ValidationResult:
        """Check consistency across multiple rendered views."""
        views_path = Path(views_dir)
        if not views_path.exists():
            return ValidationResult("multi_view", False, 0.0, {}, "Views directory not found")

        view_files = list(views_path.glob("*.png")) + list(views_path.glob("*.jpg"))
        if len(view_files) < 2:
            return ValidationResult("multi_view", False, 0.0, {}, "Need at least 2 views")

        # Would compute feature matching consistency across views
        # Placeholder
        return ValidationResult(
            "multi_view",
            True,
            0.8,
            {"num_views": len(view_files)},
            f"Found {len(view_files)} views (consistency check not implemented)"
        )

    # === Run All Checks ===

    def run_all_checks(self, views_dir: Optional[str] = None) -> List[ValidationResult]:
        """Run all validation checks."""
        results = []

        # Geometry
        results.append(self.check_watertight())
        results.append(self.check_manifold())
        results.append(self.check_normals_consistency())
        results.append(self.check_self_intersection())
        results.append(self.check_scale_consistency())

        # Physics
        results.append(self.check_center_of_mass())
        results.append(self.check_moment_of_inertia())
        results.append(self.check_physics_materials())

        # Multi-view (optional)
        if views_dir:
            results.append(self.check_multi_view_consistency(views_dir))

        return results

    def get_summary(self, results: List[ValidationResult]) -> Dict[str, Any]:
        """Get summary of validation results."""
        passed = sum(1 for r in results if r.passed)
        total = len(results)
        mean_score = np.mean([r.score for r in results])

        return {
            "total_checks": total,
            "passed": passed,
            "failed": total - passed,
            "mean_score": float(mean_score),
            "overall_passed": passed == total,
            "details": [
                {
                    "check": r.check_name,
                    "passed": r.passed,
                    "score": r.score,
                    "message": r.message
                }
                for r in results
            ]
        }


def validate_scene_file(scene_path: str, views_dir: Optional[str] = None) -> Dict[str, Any]:
    """Convenience function to validate a scene file."""
    validator = SceneValidator(scene_path)
    results = validator.run_all_checks(views_dir)
    return validator.get_summary(results)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python scene_validator.py <scene_file> [views_dir]")
        sys.exit(1)

    scene_file = sys.argv[1]
    views_dir = sys.argv[2] if len(sys.argv) > 2 else None

    summary = validate_scene_file(scene_file, views_dir)

    print(f"\n=== Scene Validation: {scene_file} ===")
    print(f"Overall: {'PASSED' if summary['overall_passed'] else 'FAILED'}")
    print(f"Score: {summary['mean_score']:.2f}")
    print(f"Checks: {summary['passed']}/{summary['total_checks']} passed\n")

    for detail in summary['details']:
        status = "✓" if detail['passed'] else "✗"
        print(f"  {status} {detail['check']}: {detail['message']} (score: {detail['score']:.2f})")