#!/bin/bash
# deploy.sh — Deploy Hyperledger Fabric network.
# Generated by hyperledger-fabric-generator

set -e

echo "╔═══════════════════════════════════════════════╗"
echo "║     HYPERLEDGER FABRIC NETWORK DEPLOY         ║"
echo "╚═══════════════════════════════════════════════╝"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
CHANNEL_NAME="mychannel"
CHAINCODE_NAME="assettransfer"
CHAINCODE_VERSION="1.0"
CHAINCODE_SEQUENCE=1
CHAINCODE_LANG="golang"
CHAINCODE_PATH="../chaincode/assettransfer"

# Environment setup
export FABRIC_CFG_PATH=$PWD
export ORDERER_CA=${PWD}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
export PEER0_ORG1_CA=${PWD}/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
export PEER0_ORG2_CA=${PWD}/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt

log_info "Starting deployment..."

# 1. Check prerequisites
log_info "Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { log_error "Docker not installed"; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { log_error "Docker Compose not installed"; exit 1; }
command -v cryptogen >/dev/null 2>&1 || { log_warn "cryptogen not in PATH, will use docker"; }
command -v configtxgen >/dev/null 2>&1 || { log_warn "configtxgen not in PATH, will use docker"; }
command -v peer >/dev/null 2>&1 || { log_warn "peer CLI not in PATH, will use docker"; }

# 2. Generate crypto material
log_info "Generating crypto material..."
if command -v cryptogen >/dev/null 2>&1; then
    cryptogen generate --config=crypto-config.yaml --output=crypto-config
else
    docker run --rm -v $(pwd):/workspace hyperledger/fabric-tools:2.5 \
        cryptogen generate --config=/workspace/crypto-config.yaml --output=/workspace/crypto-config
fi
log_info "Crypto material generated"

# 2. Generate genesis block
log_info "Generating genesis block..."
if command -v configtxgen >/dev/null 2>&1; then
    configtxgen -profile TwoOrgsOrdererGenesis -channelID system-channel -outputBlock ./channel-artifacts/genesis.block
else
    docker run --rm -v $(pwd):/workspace hyperledger/fabric-tools:2.5 \
        configtxgen -profile TwoOrgsOrdererGenesis -channelID system-channel -outputBlock /workspace/channel-artifacts/genesis.block
fi

# 3. Create channel transaction
log_info "Creating channel transaction..."
if command -v configtxgen >/dev/null 2>&1; then
    configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ./channel-artifacts/mychannel.tx -channelID mychannel
else
    docker run --rm -v $(pwd):/workspace hyperledger/fabric-tools:2.5 \
        configtxgen -profile TwoOrgsChannel -outputCreateChannelTx /workspace/channel-artifacts/mychannel.tx -channelID mychannel
fi

# 4. Create anchor peer updates
log_info "Creating anchor peer updates..."
if command -v configtxgen >/dev/null 2>&1; then
    configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate ./channel-artifacts/Org1MSPanchors.tx -channelID mychannel -asOrg Org1MSP
    configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate ./channel-artifacts/Org2MSPanchors.tx -channelID mychannel -asOrg Org2MSP
else
    docker run --rm -v $(pwd):/workspace hyperledger/fabric-tools:2.5 \
        configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate /workspace/channel-artifacts/Org1MSPanchors.tx -channelID mychannel -asOrg Org1MSP
    docker run --rm -v $(pwd):/workspace hyperledger/fabric-tools:2.5 \
        configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate /workspace/channel-artifacts/Org2MSPanchors.tx -channelID mychannel -asOrg Org2MSP
fi

log_info "Channel artifacts generated"

# 5. Start network
log_info "Starting Docker network..."
docker-compose -f docker-compose.yaml up -d

# Wait for services to be ready
log_info "Waiting for services to start..."
sleep 10

# 4. Create channel
log_info "Creating channel '$CHANNEL_NAME'..."
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG1_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=peer0.org1.example.com:7051

peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/mychannel.tx --tls --cafile $ORDERER_CA

# 5. Join peers to channel
log_info "Joining peers to channel..."
peer channel join -b mychannel.block

# Join peer0.org2
export CORE_PEER_LOCALMSPID="Org2MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG2_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
export CORE_PEER_ADDRESS=peer0.org2.example.com:9051
peer channel join -b mychannel.block

# Back to Org1
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG1_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=peer0.org1.example.com:7051

# 6. Update anchor peers
log_info "Updating anchor peers..."
peer channel update -o orderer.example.com:7050 -c mychannel -f ./channel-artifacts/Org1MSPanchors.tx --tls --cafile $ORDERER_CA
peer channel update -o orderer.example.com:7050 -c mychannel -f ./channel-artifacts/Org2MSPanchors.tx --tls --cafile $ORDERER_CA

# 7. Package chaincode
log_info "Packaging chaincode..."
cd chaincode/assettransfer
if [ "$CHAINCODE_LANG" = "golang" ]; then
    peer lifecycle chaincode package ${CHAINCODE_NAME}.tar.gz --path ${CHAINCODE_PATH} --lang golang --label ${CHAINCODE_NAME}_${CHAINCODE_VERSION}
else
    # Node.js chaincode
    peer lifecycle chaincode package ${CHAINCODE_NAME}.tar.gz --path ${CHAINCODE_PATH} --lang node --label ${CHAINCODE_NAME}_${CHAINCODE_VERSION}
fi
cd ../..

# 5. Install chaincode on peers
log_info "Installing chaincode on peers..."
peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz

# Install on Org2 peer
export CORE_PEER_LOCALMSPID="Org2MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG2_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
export CORE_PEER_ADDRESS=peer0.org2.example.com:9051
peer lifecycle chaincode install ${CHAINCODE_NAME}.tar.gz

# Back to Org1
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG1_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=peer0.org1.example.com:7051

# 6. Query installed
PACKAGE_ID=$(peer lifecycle chaincode queryinstalled | grep ${CHAINCODE_NAME}_${CHAINCODE_VERSION} | awk '{print $1}' | sed 's/,//')
log_info "Package ID: $PACKAGE_ID"

# 6. Approve chaincode
log_info "Approving chaincode..."
peer lifecycle chaincode approveformyorg \
    -o orderer.example.com:7050 \
    --channelID $CHANNEL_NAME \
    --name $CHAINCODE_NAME \
    --version $CHAINCODE_VERSION \
    --package-id $PACKAGE_ID \
    --sequence $CHAINCODE_SEQUENCE \
    --tls \
    --cafile $ORDERER_CA

# Approve on Org2
export CORE_PEER_LOCALMSPID="Org2MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG2_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
export CORE_PEER_ADDRESS=peer0.org2.example.com:9051
peer lifecycle chaincode approveformyorg \
    -o orderer.example.com:7050 \
    --channelID $CHANNEL_NAME \
    --name $CHAINCODE_NAME \
    --version $CHAINCODE_VERSION \
    --package-id $PACKAGE_ID \
    --sequence $CHAINCODE_SEQUENCE \
    --tls \
    --cafile $ORDERER_CA

# Back to Org1
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_ORG1_CA}
export CORE_PEER_MSPCONFIGPATH=${PWD}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=peer0.org1.example.com:7051

# 7. Check commit readiness
log_info "Checking commit readiness..."
peer lifecycle chaincode checkcommitreadiness \
    --channelID $CHANNEL_NAME \
    --name $CHAINCODE_NAME \
    --version $CHAINCODE_VERSION \
    --sequence $CHAINCODE_SEQUENCE \
    --tls \
    --cafile $ORDERER_CA \
    --output json

# 7. Commit chaincode
log_info "Committing chaincode..."
peer lifecycle chaincode commit \
    -o orderer.example.com:7050 \
    --channelID $CHANNEL_NAME \
    --name $CHAINCODE_NAME \
    --version $CHAINCODE_VERSION \
    --sequence $CHAINCODE_SEQUENCE \
    --tls \
    --cafile $ORDERER_CA \
    --peerAddresses peer0.org1.example.com:7051 \
    --tlsRootCertFiles $PEER0_ORG1_CA \
    --peerAddresses peer0.org2.example.com:9051 \
    --tlsRootCertFiles $PEER0_ORG2_CA

# 8. Verify commit
log_info "Verifying commit..."
peer lifecycle chaincode querycommitted --channelID $CHANNEL_NAME --name $CHAINCODE_NAME

# 8. Initialize chaincode (if needed)
log_info "Initializing chaincode..."
peer chaincode invoke \
    -o orderer.example.com:7050 \
    --channelID $CHANNEL_NAME \
    --name $CHAINCODE_NAME \
    --peerAddresses peer0.org1.example.com:7051 \
    --tlsRootCertFiles $PEER0_ORG1_CA \
    --peerAddresses peer0.org2.example.com:9051 \
    --tlsRootCertFiles $PEER0_ORG2_CA \
    --isInit \
    -c '{"function":"InitLedger","Args":[]}'

# 9. Test chaincode
log_info "Testing chaincode..."
peer chaincode query -C mychannel -n assettransfer -c '{"function":"QueryAllAssets","Args":[]}'

log_info "╔═══════════════════════════════════════════════╗"
log_info "║     DEPLOYMENT COMPLETED SUCCESSFULLY!        ║"
log_info "╚═══════════════════════════════════════════════╝"
log_info "Network is ready. You can now:"
log_info "  - Test chaincode: peer chaincode query -C mychannel -n assettransfer -c '{\"function\":\"QueryAllAssets\",\"Args\":[]}'"
log_info "  - Invoke transactions: peer chaincode invoke -o orderer.example.com:7050 --channelID mychannel --name assettransfer --peerAddresses peer0.org1.example.com:7051 --tlsRootCertFiles \$PEER0_ORG1_CA --peerAddresses peer0.org2.example.com:9051 --tlsRootCertFiles \$PEER0_ORG2_CA -c '{\"function\":\"CreateAsset\",\"Args\":[\"asset1\",\"blue\",5,\"Org1\",\"300\"]}'"
log_info "  - Access Explorer: http://localhost:8080"
log_info "  - Run benchmarks: npx caliper launch manager --caliper-workspace ./caliper --caliper-benchconfig caliper/caliper-config.yaml --caliper-networkconfig caliper/network-config.yaml"

exit 0